### ISSUE TITLE
SQLCipherUtils.getDatabaseState always throws exception for encrypted database

### ISSUE THREAD

**Issue by afink170** [sqlcipher/android-database-sqlcipher#404] opened 2018-11-23 21:30 UTC
### Expected Behavior
getDatabaseState should return ENCRYPTED if the database is already encrypted

### Actual Behavior
The getDatabaseState method relies on SQLiteDatabase.openDatabase by supplying an empty password when opening the database.  If openDatabase throws an exception (because it needs a passphrase), it is caught and the method returns ENCRYPTED.  If it is successful, it returns UNENCRYPTED.  The logic of the method works as intended, but the side effect is that whenever getDatabaseState is called on an encrypted database, in addition to returing ENCRYPTED (as it should), it logs "SQLiteException: file is not a database" to the LogCat.  This is not a huge problem, but it is quite annoying to have an exception and stack trace printed to the log every time the app opens, as I use this method to handle some database encryption operations whenever the app launches.

`E/Database: file is not a database: , while compiling: select count(*) from sqlite_master;
    net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
        at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
        at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
        at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
        at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
        at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
        at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
        at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1867)
        at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1785)
        at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2486)
        at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2415)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1149)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1116)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1065)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1019)
        at com.commonsware.cwac.saferoom.SQLCipherUtils.getDatabaseState(SQLCipherUtils.java:62)
        at com.commonsware.cwac.saferoom.SQLCipherUtils.getDatabaseState(SQLCipherUtils.java:46)
        at edu.usm.cs.csc414.pocketfinances.AppClass.onCreate(AppClass.java:118)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6056)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

### Steps to Reproduce
Call the SQLCipherUtils.getDatabaseState method on a database that is already encrypted.  It will return ENCRYPTED as it should, but an SQLiteException will also be thrown.

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version:  3.5.9

**Comment by hoordev** [comment] 2018-11-23 21:48
+1

**Comment by developernotes** [comment] 2018-11-27 15:59
Hi @afink170,

Alternatively, you could attempt to read the first 16 bytes of the database file to determine if you are using a plain-text SQLite file. Plain-text SQLite will use [a magic string value](https://www.sqlite.org/fileformat.html#magic_header_string) of `SQLite format 3`, whereas a SQLCipher database will store the per database salt in that location. Since this appears to be specific to the implementation of SafeRoom, it might be worth checking with @commonsguy about the possibility of change.

**Comment by commonsguy** [comment] 2018-11-27 16:16
@developernotes My interpretation of the issue is: could you not log that yourself? You are already throwing the `Exception`, so the decision to log or not-log is the app's.

There is nothing that I can change at the SafeRoom level, other than to remove this method entirely from the library, as I cannot stop SQLCipher for Android from logging things.

**Comment by afink170** [comment] 2018-11-27 20:43
Hi @commonsguy and @developernotes,

I suppose that what I was suggesting in the issue is that the getDatabaseState method would be better off not relying on whether SQLiteDatabase.openDatabase throws an exception to determine whether the database is encrypted or not.  

I certainly understand why the getDatabaseState method is implemented the way that it is, as attempting to open the database seems to be the most obvious and simplest way to  determine the database's encryption state.  However, since an exception is thrown in the SQLiteDatabase.openDatabase method if the database is encrpyted, an error is logged, even though as far as I am concerned, there was no error.  The getDatabase method returns a valid ENCRYPTED state, and it works.

So since the SQLiteDatabase.openDatabase method should not be changed, as it very well ought to throw an exception if the database can't be opened, I suppose that the change would, as @developernotes suggested, need to occur at the SafeRoom level.  I was suggesting that the getDatabaseState method could instead rely on some other logic to determine the database encryption state.  I do not know much about interacting directly with SQLite databases, and you would definitely know much more about that than I do, so I won't try to suggest any alternatives (mostly because I wouldn't know where to start anyway), but the suggestion of reading the first 16 bytes of the database file sounds interesting, so I may look into trying to implement that in leu of the getDatabaseState method.

All of that being said, the getDatabaseState method does do what it is supposed to do, as the exception thrown by SQLiteDatabase.openDatabase is just a small side effect, so it isn't really an "issue."  It is just a nitpicky thing that I wanted to bring to the library developers' attention.

**Comment by sjlombardo** [comment] 2018-11-27 20:47
@afink170 - agreed, I believe that is what @developernotes was suggesting as well, that perhaps the getDatabaseState could simply check the header of the database. If the first 16 bytes are `SQLite format 3` then it is `UNENCRYPTED`, else assume it is `ENCRYPTED`.

**Comment by commonsguy** [comment] 2018-11-27 21:23
The proposed approach seems fragile compared with trying to actually open the database with an empty passphrase, which is my current implementation.

**Comment by developernotes** [comment] 2018-12-03 14:11
Hi @afink170 

Thank you for reaching out, I wanted to circle back to this now that we have SQLCipher 4 released. We do not have any plans to changing the logging that occurs within SQLCipher for Android when an exception is thrown due to an invalid key. The logging is intentional, which is triggered lower within the library stack (JNI) and can be useful for debugging and analysis of failed open events. At this time I am going to close this issue.

**Closed by developernotes** 2018-12-03 14:11 UTC
