### ISSUE TITLE
file is not a database: , while compiling: select count(*) from sqlite_master;

### ISSUE THREAD

**Issue by bacancy-mohit** [sqlcipher/android-database-sqlcipher#389] opened 2018-06-12 12:52 UTC
SQLCipher for Android version: 'net.zetetic:android-database-sqlcipher:3.5.9@aar'

What I am Doing : 
-I am making app using Sqlite Cipher.at begining when i start with Sqlite cipher encrypt DB it working properly in whole app (I build test project with Sqlite Cipher.).

but now flow was change.  so I unintall app and doing step below.

    - initially, I encrypt the database  with ""( means plaintext DB).
    - now in one case from a server tag I change It encrypting the database with Key.

 ```
File unencryptedDatabase = originalFile;
            File encryptedDatabase = mContext.getDatabasePath("encrypted.db");
            try {
                db.close();
                db = SQLiteDatabase.openOrCreateDatabase(unencryptedDatabase, "", null);
                db.rawExecSQL(String.format("ATTACH DATABASE '%s' AS encrypted KEY '%s'",
                        encryptedDatabase.getAbsolutePath(), encrypt));
                db.rawExecSQL("select sqlcipher_export('encrypted')");
                db.rawExecSQL("DETACH DATABASE encrypted");
                db.close();
                SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(mContext);
                prefs.edit().putString("secretDatabaseKey", encrypt).apply();
                Log.e("====", "====");
                unencryptedDatabase.delete();
                encryptedDatabase.renameTo(originalFile);
            } catch (Exception e) {
                e.printStackTrace();
            }
```

> Database Encryption Done without error .
> 
> -  retrive data from database with my KEY / close app and start again 
> but when I try retriving data from database It fire error.
> 
> 
> 

=================================

 ```
 net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
        at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
        at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
        at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
        at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
        at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
        at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
        at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1867)
        at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1785)
        at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2486)
        at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2415)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1149)
        at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1212)
        at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
        at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:129)
```

**Comment by developernotes** [comment] 2018-06-12 13:03
Hi @bacancy-mohit 

Since your application originally only dealt with a plain-text SQLite database, it is possible you are attempting to access the file path to the plain-text SQLite database, but providing the password to open it? Can you pull the database off the device and verify you it is being encrypted?

**Comment by bacancy-mohit** [comment] 2018-06-13 09:45
Yes Its encrypted ,
I checked it .
but I cant access that database with Key.
I check Key also when I am encrypt it .
And also check at database access.

**Comment by developernotes** [comment] 2018-06-13 14:45
Hi @bacancy-mohit 

>Yes Its encrypted ,
I checked it .
but I cant access that database with Key.
I check Key also when I am encrypt it .

Is it encrypted with SQLCipher using the same password? If so, what version of SQLCipher is used to encrypt the database file?

>i just want to do "" password -> "xyz" password. using our sqlite cipher lib only.

If you are using an empty string for the password (and can access the content), the database file would not be encrypted. If you are attempting to migrate from a plain-text SQLite database file to a SQLCipher encrypted database, you will need to utilize the [`sqlcipher_export(...)`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export), specifically refer to example 1 in the documentation.

**Comment by bacancy-mohit** [comment] 2018-06-14 06:49
>  what version of SQLCipher is used to encrypt 

as I said before  at the top Question : SQLCipher for Android version: **'net.zetetic:android-database-sqlcipher:3.5.9@aar'**

> If you are using an empty string for the password (and can access the content), the database file would not be encrypted. 

Yes sir thats I know  and  already implement NonEncrepted database from ""  password.

but now schenario is that I wan tto change password In one case that my server having check box to encrypt database true/false.

If I get true then i have to change password "" -> "xyz"(or any random password.) then database Encrypted succesfully .

but now i cant access database with my key ( Ex. xyz).
for Encryption I done code as like below.



`File unencryptedDatabase = originalFile;
           File encryptedDatabase = mContext.getDatabasePath("encrypted.db");
           try {
               db.close();
               db = SQLiteDatabase.openOrCreateDatabase(unencryptedDatabase, "", null);
               db.rawExecSQL(String.format("ATTACH DATABASE '%s' AS encrypted KEY '%s'",
                       encryptedDatabase.getAbsolutePath(), encrypt));
               db.rawExecSQL("select sqlcipher_export('encrypted')");
               db.rawExecSQL("DETACH DATABASE encrypted");
               db.close();
               SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(mContext);
               prefs.edit().putString("secretDatabaseKey", encrypt).apply();
               Log.e("====", "====");
               unencryptedDatabase.delete();
               encryptedDatabase.renameTo(originalFile);
           } catch (Exception e) {
               e.printStackTrace();
           }`

**Comment by developernotes** [comment] 2018-06-14 14:33
Hello @bacancy-mohit 

I would suggest you try to open an separate connection to the encrypted database and attempt to read data from a table before you perform the file rename. We have a test within the SQLCipher for Android test suite [here](https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/app/src/main/java/net/zetetic/tests/ImportUnencryptedDatabaseTest.java) that showcases encrypting a plain-text SQLite database. Also, you might wish to verify you are always sourcing the same password value, possibly changing it to a static value to rule out your storage of the key.

**Comment by bacancy-mohit** [comment] 2018-06-14 14:44
Ok, I already double check the password.
But one scenario remaining before rename database check table value. 
I will update you soon.

**Comment by bacancy-mohit** [comment] 2018-06-15 15:08
https://expirebox.com/download/dd7735c50f82413ff97f3cc179ee35b7.html

Check That file I attached demo and both demo database and encrypted database.

**Comment by developernotes** [comment] 2018-06-15 15:14
Hello @bacancy-mohit 

Are you able to create a reproducible test in the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) that we can investigate further?

**Comment by developernotes** [comment] 2018-06-15 16:03
Hello @bacancy-mohit 

I was able to query your `encrypted.db` database file within the SQLCipher for Android test suite successfully. I've included the sample test I put together below. I would suggest you attempt to narrow down the cause of the issue further within your application as it does not appear to be an issue with the library itself. Since we reserve Github Issues for reporting issues with the software itself, I am going to close this ticket for now. Alternatively, if you have questions about the library, our SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher) is a good place to start.

```
package net.zetetic.tests;

import net.sqlcipher.Cursor;
import net.sqlcipher.database.SQLiteDatabase;
import net.zetetic.ZeteticApplication;

import java.io.File;

public class AccessDatabaseTest extends SQLCipherTest {
  @Override
  public boolean execute(SQLiteDatabase database) {
    database.close();
    try {
      int rows = 0;
      String filename = "encrypted.db";
      ZeteticApplication.getInstance().extractAssetToDatabaseDirectory(filename);
      File databasePath = ZeteticApplication.getInstance().getDatabasePath(filename);
      database = SQLiteDatabase.openDatabase(databasePath.getAbsolutePath(), "test", null, SQLiteDatabase.OPEN_READWRITE);
      if(database != null){
        Cursor cursor = database.rawQuery("SELECT COUNT(*) FROM sqlite_master;", new Object[]{});
        if(cursor != null){
          cursor.moveToFirst();
          rows = cursor.getInt(0);
          cursor.close();
        }
      }
      return rows > 0;
    } catch (Exception e) {
      return false;
    }
  }

  @Override
  public String getName() {
    return "Access Database File Test";
  }
}

```

**Closed by developernotes** 2018-06-15 16:03 UTC
