### ISSUE TITLE
"Jar found at unexpected path" warning

### ISSUE THREAD

**Issue by xsveda** [sqlcipher/android-database-sqlcipher#239] opened 2016-06-27 05:24 UTC
During a Gradle build I see these warnings:

```
Jar found at unexpected path (jni/sqlcipher-javadoc.jar) in C:\Users\User\.gradle\caches\modules-2\files-2.1\net.zetetic\android-database-sqlcipher\3.5.0\501f5791f663e4c91346ec15
36c3ca8550646d02\android-database-sqlcipher-3.5.0.aar and will be ignored. Jars should be placed inside 'jars' folder to be merged into dex. Jars that are in assets/ or res/raw/ wi
ll be copied as-is.
Jar found at unexpected path (jni/sqlcipher.jar) in C:\Users\User\.gradle\caches\modules-2\files-2.1\net.zetetic\android-database-sqlcipher\3.5.0\501f5791f663e4c91346ec1536c3ca85
50646d02\android-database-sqlcipher-3.5.0.aar and will be ignored. Jars should be placed inside 'jars' folder to be merged into dex. Jars that are in assets/ or res/raw/ will be co
pied as-is.
```

The "problem" is that in AAR there are Java classes placed correctly in root `classes.jar` file but copied also in `jni` folder as `sqlcipher.jar` together with javadoc in `sqlcipher-javadoc.jar`.

SQLCipher: 3.5
Gradle: 2.12
Android Gradle plugin: 2.1.2
Android build tools: 23.0.2

**Comment by developernotes** [comment] 2016-06-27 13:42
Hi @xsveda 

Thanks for the report, we will look into the AAR packaging we create to see if it can resolved in a future release. Thanks!

**Comment by StAlex74** [comment] 2016-08-16 07:18
Any news ? Got the same error after upgrade Android Studio to 2.1.3.
env:
Gradle 2.14.1
compileSdkVersion 23
buildToolsVersion "23.0.2"
compile 'net.zetetic:android-database-sqlcipher:3.5.3@aar'
classpath 'com.android.tools.build:gradle:2.1.3'

**Comment by developernotes** [comment] 2016-08-16 13:02
Hi @StAlex74 

There have not been any changes to the build packaging at this point. Are you unable to compile your application?

**Comment by StAlex74** [comment] 2016-08-16 13:31
> Are you unable to compile your application?
With aar dependency - yes, project is not compile.
As temporary workaround, I am just download .so && .jar and push them into the project structure with correct paths.

**Comment by developernotes** [comment] 2016-08-16 13:55
Hi @StAlex74 

I just created a demo application using the 3.5.3 AAR package within Android Studio 2.1.3. While the Gradle Console does output that message, it does not prevent the application from compiling with SQLCipher for Android, nor running.

**Comment by StAlex74** [comment] 2016-08-16 14:40
Strange behavior. I'm rolling back to compile with aar-dep, and app now is compiled successfully...
o_O What is going on?  When I faced with the aar-dep failure, project has not seen sqlcipher imports:
```
import net.sqlcipher.database.SQLiteDatabase;
import net.sqlcipher.database.SQLiteException;
```
until I place the so & jar files as I mentioned above
and right now I can't reproduce an initial problem. When I looks in the 
`build/intermediates/exploded-aar/net.zetetic/android-database-sqlcipher`
directory I see the `jars` directory which contains library's `classes.jar`
in the same time, aar from the log-file (from the `~/.gradle/caches` dir) **does not** contains that dir and `classes.jar` placed in the root of aar-file. Is there 'special behavior' which relocates the _default_ classes.jar into the _right_ place ? And in some cases that 'special behavior' not working?

**Comment by developernotes** [comment] 2016-08-17 18:59
Hi @StAlex74 

I'm glad to hear utilizing the AAR packaging is working well for you again. I am not certain what would cause the behavior you saw previously.

**Comment by StAlex74** [comment] 2016-08-18 06:42
> I am not certain what would cause the behavior you saw previously.

I mean about how AS/Gradle-plugin perform unpacking an aar-file and works with its contents. Why this procedure (I claim that as 'special behavior') fails with aar's mandatory `classes.jar` and not provide contents for my project. As a side note, that happened right after upgrading AS and first boot after that.

**Comment by developernotes** [comment] 2016-08-18 12:52
Hi @StAlex74 

Thank you for sharing some additional details, we will keep an eye out for this behavior in the future from others. Thanks!

**Closed** 2016-11-21 18:26 UTC

**Comment by xsveda** [comment] 2016-11-22 06:44
This issue was closed but the original problem is still reproducible on latest version `3.5.4`:
```
Jar found at unexpected path (jni/sqlcipher-javadoc.jar) in C:\Users\User\.gradle\caches\modules-2\files-2.1\net.zetetic\android-database-sqlcipher\3.5.4\ae14715c148b40e3f1c4479e7efefb74de669abf\android-database-sqlcipher-3.5.4.aar and will be ignored. Jars should be placed inside 'jars' folder to be merged into dex. Jars that are in assets/ or res/raw/ will be copied as-is.
Jar found at unexpected path (jni/sqlcipher.jar) in C:\Users\User\.gradle\caches\modules-2\files-2.1\net.zetetic\android-database-sqlcipher\3.5.4\ae14715c148b40e3f1c4479e7efefb74de669abf\android-database-sqlcipher-3.5.4.aar and will be ignored. Jars should be placed inside 'jars' folder to be merged into dex. Jars that are in assets/ or res/raw/ will be copied as-is.
```

@developernotes: can you re-open this one, please?

**Comment by developernotes** [comment] 2016-11-22 16:57
Hi @xsveda 

This is somewhat of a by product of using ant in conjunction with maven to produce the AAR package. I think long term we may migrate over to a gradle build. I will see if I can adjust the bundling for the next release, however these warnings do not prevent normal operation.

**Comment by sschuberth** [comment] 2017-03-13 12:29
@developernotes But as the issue itself persists, mind reopening it to account for that fact?

**Comment by developernotes** [comment] 2017-03-13 13:56
Hello @sschuberth 

Glad to hear it is working properly for you now. You should likely switch over to 3.5.6, our latest release if you are using 3.5.5. Thanks!
