### ISSUE TITLE
net.sqlcipher.database.SQLiteDiskIOException: error code 10: disk I/O error

### ISSUE THREAD

**Issue by ouyangpeng** [sqlcipher/android-database-sqlcipher#409] opened 2018-12-25 02:34 UTC
Hey, team, my application crashed.  devName is MI 8，android 9.0

Here's the crash log:
![image](https://user-images.githubusercontent.com/5885735/50409764-08c39a80-0830-11e9-8849-7fd32d44fbe7.png)

```java
[E][2018-12-23 +8.0 16:10:02.401][18375, 3657][:][OrmLiteDao.java, insert, 125][
net.sqlcipher.database.SQLiteDiskIOException: error code 10: disk I/O error
	at net.sqlcipher.database.SQLiteStatement.native_execute(Native Method)
	at net.sqlcipher.database.SQLiteStatement.executeInsert(SQLiteStatement.java:83)
	at com.j256.ormlite.sqlcipher.android.AndroidDatabaseConnection.insert(AndroidDatabaseConnection.java:158)
	at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
	at com.j256.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
	at com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
	at com.xtc.data.phone.database.dao.OrmLiteDao.insert(OrmLiteDao.java:123)
	at com.xtc.data.phone.database.dao.OrmLiteDao.insert(OrmLiteDao.java:113)
	at com.xtc.watch.dao.dialog.DialogMsgDao.create(DialogMsgDao.java:131)
	at com.xtc.watch.service.weichat.impl.DialogMsgServiceImpl.Hawaii(DialogMsgServiceImpl.java:1711)
	at com.xtc.watch.service.weichat.impl.DialogMsgServiceImpl.sendSliceVoice(DialogMsgServiceImpl.java:813)
	at com.xtc.watch.view.weichat.presenter.VoiceRecordPresenter$StartRecorderListener.onRecording(VoiceRecordPresenter.java:569)
	at com.xtc.audio.record.RecorderManager.Hawaii(RecorderManager.java:448)
	at com.xtc.audio.record.RecorderManager.Hawaii(RecorderManager.java:29)
	at com.xtc.audio.record.RecorderManager$RecordDataThread.run(RecorderManager.java:376)
```
And this exception anomaly recurs，when I uninstall and reinstall the app, it returned to normal.
please help me!

![image](https://user-images.githubusercontent.com/5885735/50409754-fe090580-082f-11e9-8ebc-258a10e09612.png)

**Comment by sjlombardo** [comment] 2018-12-26 23:56
Is your database on external storage? Are you certain that the device FS isn't full?

**Comment by ouyangpeng** [comment] 2018-12-28 09:07
My database is in the directory ： / data / data / com. xtc. watch / databases . 
The disk is not full. 

the website  (https://www.sqlite.org/rescode.html#ioerr)   sees a description of this issue.

![image](https://user-images.githubusercontent.com/5885735/50509988-e2695d80-0ac2-11e9-934c-8d33ad1dd9f5.png)

>(10) SQLITE_IOERR
The SQLITE_IOERR result code says that the operation could not finish because the operating system reported an I/O error.
A full disk drive will normally give an SQLITE_FULL error rather than an SQLITE_IOERR error.
There are many different extended result codes for I/O errors that identify the specific I/O operation that failed.


![image](https://user-images.githubusercontent.com/5885735/50510021-0036c280-0ac3-11e9-8d7a-1cf48d5662c7.png)

```
SQLITE_IOERR_ACCESS (3338)
SQLITE_IOERR_BLOCKED (2826)
SQLITE_IOERR_CHECKRESERVEDLOCK (3594)
SQLITE_IOERR_CLOSE (4106)
SQLITE_IOERR_CONVPATH (6666)
SQLITE_IOERR_DELETE (2570)
SQLITE_IOERR_DELETE_NOENT (5898)
SQLITE_IOERR_DIR_CLOSE (4362)
SQLITE_IOERR_DIR_FSYNC (1290)
SQLITE_IOERR_FSTAT (1802)
SQLITE_IOERR_FSYNC (1034)
SQLITE_IOERR_GETTEMPPATH (6410)
SQLITE_IOERR_LOCK (3850)
SQLITE_IOERR_MMAP (6154)
SQLITE_IOERR_NOMEM (3082)
SQLITE_IOERR_RDLOCK (2314)
SQLITE_IOERR_READ (266)
SQLITE_IOERR_SEEK (5642)
SQLITE_IOERR_SHMLOCK (5130)
SQLITE_IOERR_SHMMAP (5386)
SQLITE_IOERR_SHMOPEN (4618)
SQLITE_IOERR_SHMSIZE (4874)
SQLITE_IOERR_SHORT_READ (522)
SQLITE_IOERR_TRUNCATE (1546)
SQLITE_IOERR_UNLOCK (2058)
SQLITE_IOERR_WRITE (778)

```

but ii don't see the Extended Result Code List in my crash log 

@sjlombardo

**Comment by developernotes** [comment] 2018-12-28 16:13
Hi @ouyangpeng 

Is this something that you can recreate within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

**Comment by sjlombardo** [comment] 2018-12-28 20:53
@ouyangpeng  - Another option would be to remove SQLCipher and using a non-encrypted database (i.e. via the standard SQLite API). If you observe the same errors with a standard database then you can be sure that the problem is not with SQLCipher. For what it's worth we have had reports of IO errors like this in the past, and they have appeared to be issues with the OS, particularly when the file system is approaching full.

**Comment by ouyangpeng** [comment] 2018-12-30 06:55
@developernotes  
I didn't do unit tests in my app ,this problem was discovered after a complaint was sent to one of the apps that had been published to users.

**Comment by ouyangpeng** [comment] 2018-12-30 06:57
@sjlombardo 
It's a special case, so far only one user complained, but the disk is not full. 
We did use SQL Cipher for encryption and probably won't remove it later.

**Comment by sjlombardo** [comment] 2018-12-31 16:08
Hello @ouyangpeng - thanks for getting back to us.  I/O errors are likely being caused at the OS level, and in our experience have nothing to do with SQLCipher. It would be very difficult for us to even speculate in this case since its an isolated incident. If you see this again, or you are able to come up with a scenario that reliably reproduces this please let us know. I will close this ticket for the time being.

**Closed by sjlombardo** 2018-12-31 16:08 UTC
