### ISSUE TITLE
java.lang.IllegalStateException: database /data/user/0/<app>/databases/<app>_encrypted.db already closed

### ISSUE THREAD

**Issue by zkrige** [sqlcipher/android-database-sqlcipher#628] opened 2023-06-03 10:07 UTC
### Expected Behavior
DB stays open

### Actual Behavior
DB is being closed at some point
```
at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:57)
at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:91)
at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:50)
at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:2019)
at net.sqlcipher.database.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1802)
at net.sqlcipher.database.SQLiteDatabase.query(SQLiteDatabase.java:1754)
at net.sqlcipher.database.SQLiteDatabase.query(SQLiteDatabase.java:1886)
```

### Steps to Reproduce
....
SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):
4.54 community

SQLCipher for Android version:
4.54

Are you able to reproduce this issue within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?
No

The db seems to behave for a while, and then at some point, it gets closed. I have multiple reads and writes happening from different background tasks.

This is an existing app that was using standard android sqlite. I've just done a drop in replacement for the sqlcipher version. If I revert to standard android sqlite, it works fine

**Comment by sjlombardo** [comment] 2023-07-17 18:41
There is not enough information here to determine what the problem is. Are all of the threads you mentioned sharing a single database connection? Or does each thread have it's own separate connection? Have you determined if there are any exceptions being thrown that might be causing one of your application's threads to close the database connection prematurely?

**Comment by zkrige** [comment] 2023-07-18 05:11
Im having a hard time creating a test app that reproduces this, but im definitely seeing quite a bit of it in our production app

**Comment by zkrige** [comment] 2023-07-18 07:32
here's a screenshot from crashlytics showing a bunch of crashes in our prod app

<img width="1304" alt="image" src="https://github.com/sqlcipher/android-database-sqlcipher/assets/968412/a9ea4031-4388-4fe4-ab14-09e580ef177d">

**Comment by zkrige** [comment] 2023-07-18 14:24
We don't have _any_ calls to close db connections. The DB is provided via a singleton that gets instantiated early on in app lifecycle. It is never closed or released.

preliminary testing points to something in the query component going awry but I can't seem to pin down the exact scenario causing it. The reference count is at some point decremented once too many and the library then thinks the db is closed

**Comment by zkrige** [comment] 2023-07-19 07:14
I'm not using this library anymore - have moved to https://github.com/sqlcipher/sqlcipher-android/ - will monitor and see if it continues

**Comment by sjlombardo** [comment] 2023-09-24 18:03
Closing as logged against the wrong library, discussion moved to referenced ticket.

**Closed by sjlombardo** 2023-09-24 18:03 UTC
