### ISSUE TITLE
Android 7.0 Native crashes due to sqlcipher library and NDK restrictions

### ISSUE THREAD

**Issue by neeleshatale** [sqlcipher/android-database-sqlcipher#371] opened 2018-01-31 09:58 UTC
I'm receiving following crash on Android 7.0 Samsung S8 and many other such native crashes:

```
backtrace:
#00  pc 000000000005da7c  /system/lib64/libbinder.so (_ZN7android6Parcel14freeDataNoInitEv+16)
#01  pc 00000000000f8538  /system/lib64/libandroid_runtime.so
#02  pc 0000000002a4fa24  /system/framework/arm64/boot-framework.oat (android.os.Parcel.nativeDestroy+128)
#03  pc 0000000002a4ee10  /system/framework/arm64/boot-framework.oat (android.os.Parcel.destroy+76)
#04  pc 0000000002a5396c  /system/framework/arm64/boot-framework.oat (android.os.Parcel.finalize+40)
#05  pc 000000000068a6e0  /system/framework/arm64/boot-core-libart.oat (java.lang.Daemons$FinalizerDaemon.doFinalize+140)
#06  pc 000000000068a9bc  /system/framework/arm64/boot-core-libart.oat (java.lang.Daemons$FinalizerDaemon.runInternal+520)
#07  pc 000000000068a054  /system/framework/arm64/boot-core-libart.oat (java.lang.Daemons$Daemon.run+96)
#08  pc 000000000065fda0  /system/framework/arm64/boot.oat (java.lang.Thread.run+60)
#09  pc 00000000000d25b4  /system/lib64/libart.so (art_quick_invoke_stub+580)
#10  pc 00000000000df6e4  /system/lib64/libart.so (_Z N3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+212)
#11  pc 0000000000475fc4  /system/lib64/libart.so (_ZN3artL18InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS_8ArgArrayEPNS_6JValueEPKc+108)
#12  pc 0000000000477598  /system/lib64/libart.so (_ZN3art35InvokeVirtualOrInterfaceWithJValuesERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectP10_jmethodIDP6jvalue+372)
#13  pc 00000000004988a8  /system/lib64/libart.so (_ZN3art6Thread14CreateCallbackEPv+1104)
#14  pc 00000000000770f4  /system/lib64/libc.so (_ZL15__pthread_startPv+204)
#15  pc 000000000001e7d0  /system/lib64/libc.so (__start_thread+16)
```

This crash was logged on play store. It keeps repeating for every build update we provide on play store.

Below library is used in my app, which is the only library that uses jni code from NDK.

    `compile 'net.zetetic:android-database-sqlcipher:3.5.9@aar'`
    `compile 'org.greenrobot:greendao:3.0.1'`

[SQLCipher Library from Github](https://github.com/sqlcipher/android-database-sqlcipher)

[Greendao Library from Github](https://github.com/greenrobot/greenDAO)

[NDK Restrictions on Android 7.0](https://developer.android.com/about/versions/nougat/android-7.0-changes.html#ndk)

Please help to resolve this crash issue. It is increasing day by day for my app. See below image:

[Play store crashes](https://i.stack.imgur.com/0sIOi.png)

[SO Question Link](https://stackoverflow.com/q/48539031/8276680)

**Comment by developernotes** [comment] 2018-01-31 14:27
Hi @neeleshatale 

Is there a specific reason you feel this crash is related to SQLCipher for Android? The trace itself doesn't reference our library, nor do we link to any system libraries regarding the restriction you reference. To rule out SQLCipher for Android, would you try running the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) on your Samsung S8 device and let us know your results? Thanks!

**Comment by neeleshatale** [comment] 2018-02-01 16:54
Hello,
Thanks for quick response.
I have executed the SQLCipher for Android test suite on your Samsung S8 , and samsung s6,
test suite works fine during all tests and results are all OK,
but when i press back app gets stopped saying SQLCipher Test Suite has stopped,

please find attached images.

![screenshot_20180201-221936](https://user-images.githubusercontent.com/20472096/35691401-6a484208-079e-11e8-8d82-ab2d96992315.png)
![screenshot_20180201-222133](https://user-images.githubusercontent.com/20472096/35691402-6a7b38d4-079e-11e8-8c9d-af6549f6bbd4.png)
![screenshot_20180201-200120](https://user-images.githubusercontent.com/20472096/35691403-6ac6d8f2-079e-11e8-96fb-6fdf64865cc1.png)
![screenshot_20180201-210549](https://user-images.githubusercontent.com/20472096/35691404-6aefdab8-079e-11e8-9909-0c398d5ac976.png)

**Comment by developernotes** [comment] 2018-02-01 16:59
Hi @neeleshatale 

Thank you for running the test suite on your devices. It appears that SQLCipher for Android itself is running properly on your devices. If you are able to recreate a test scenario, in either the test suite application, or a small isolated application, that showcases an issue with SQLCipher for Android, we would be happy to investigate further. We will close this ticket for now. Please feel free to open a new ticket if you are able to identify any more specific information that points to SQLCipher as the cause. Thanks!

**Closed by developernotes** 2018-02-01 16:59 UTC
