### ISSUE TITLE
Published aar file includes unnecessary resources.

### ISSUE THREAD

**Issue by rharter-phunware** [sqlcipher/android-database-sqlcipher#205] opened 2015-12-02 19:19 UTC
As you can see, the sqlcipher AAR provided through maven includes some extra junk that isn't (or shouldn't be) required.  For instance, the inclusion of the icon.png (from really old template projects), main layout xml file, and a `strings.xml` file that contains an `app_name` (you're a library, you don't have an app name) and a `hello_world` string.

<img width="185" alt="screen shot 2015-12-02 at 1 11 41 pm" src="https://cloud.githubusercontent.com/assets/15617196/11541280/ff7d3a40-98f6-11e5-94f8-6c5996689bc0.png">

These should be excluded from the aar so they don't pollute client projects.

**Comment by developernotes** [comment] 2015-12-02 20:29
Hi @rharter-phunware 

Thanks for the comment.  I looks like AAR [format](http://tools.android.com/tech-docs/new-build-system/aar-format) requires the `res` folder to be present, but obviously not the `icon.png` files, nor the `strings.xml`.  We can look into this in the future, or you are welcome to submit a pull request as well.  Thanks!

**Comment by rharter-phunware** [comment] 2015-12-02 20:35
Thanks @developernotes.  I made this comment with the wrong account, so I'm moving over here :)

I quickly checked this out for that exact purpose, and it looks like part of the problem is that the sample app is mixed in with the library, which seems like another problem.  Ideally these would be separate modules so that when I include your library I'm not also including your sample code.  Given the reliance on automake this is a little harder for us standard Android developers.  

I think I'll take a look at this and see what it would take.  In addition, would you guys be open to moving to gradle now that it has official NDK support, assuming there aren't hiccups.  I'd be happy to look at that, as well.

**Comment by developernotes** [comment] 2015-12-02 20:43
Hi @rharter-phunware 

>I quickly checked this out for that exact purpose, and it looks like part of the problem is that the sample app is mixed in with the library, which seems like another problem.

Yes, I imagine that is likely the root cause as well.  I think at this point in time it likely makes sense to remove that sample application from the source tree; I don't believe it is adding a lot of additional value at this point.

>In addition, would you guys be open to moving to gradle now that it has official NDK support, assuming there aren't hiccups.

Moving to gradle as a build system is something I would like to do in the future, however we will need to verify it meets all of our current needs before we replace the current build system.  Fixing this issue shouldn't be predicated on a move to gradle.

**Comment by developernotes** [comment] 2016-03-22 18:52
This has been removed and the fix will be included within the next release.

**Closed by developernotes** 2016-03-22 18:52 UTC
