### ISSUE TITLE
Build failure for v4.3.0

### ISSUE THREAD

**Issue by akallabeth** [sqlcipher/android-database-sqlcipher#503] opened 2020-04-09 11:47 UTC
### Expected Behavior
Build succeedes

### Actual Behavior
Build aborts at `ndk-build` step in `Task :android-database-sqlcipher:buildNative FAILED`

### Steps to Reproduce
1. Fresh installed android SDK
1. Using side-by-side NDK (version does not matter, tried from `16` up to `21`)
1. Fresh clone of this repository, check out tag `v4.3.0` (same is true for master)
1. `make init && make build-debug`
   1. See OpenSSL being build
   1. See build abort at `sqlcipher` step

**Comment by developernotes** [comment] 2020-04-09 13:06
Hi @akallabeth 

>Build aborts at ndk-build step in Task :android-database-sqlcipher:buildNative FAILED
>See build abort at sqlcipher step

What are the details provided in the error message specifically? 

>Using side-by-side NDK (version does not matter, tried from 16 up to 21)

You will need to use NDK version `r20`.

**Comment by akallabeth** [comment] 2020-04-09 13:55
* Is that `20.0.5594570` or `20.1.5948944` from `sdkmanager`? (Sorry, always get confused by google versioning) or are there actual differences between `sdkmanager` and direct downloads?
* how do I get the output of native build tools in a gradle build? (gradle is very verbose but tends to lack the information actually relevant)

**Comment by developernotes** [comment] 2020-04-09 14:01
Hi @akallabeth 

>Is that 20.0.5594570 or 20.1.5948944 from sdkmanager? (Sorry, always get confused by google versioning) or are there actual differences between sdkmanager and direct downloads?

I believe you want 20b, which maps to `"20.1.5948944"`

>how do I get the output of native build tools in a gradle build? (gradle is very verbose but tends to lack the information actually relevant)

Try running the following command to get further details. I agree Gradle can be verbose, but we need to start somewhere to further narrow down the cause of your build error. Is there a reason you need to build the library from source?

```
./gradlew android-database-sqlcipher:buildNative --debug
```

**Comment by akallabeth** [comment] 2020-04-09 14:08
[log.zip](https://github.com/sqlcipher/android-database-sqlcipher/files/4456597/log.zip)


attached the output, but it only tells `ndk-build` failed :/

**Comment by akallabeth** [comment] 2020-04-09 14:11
@developernotes and yes, we try to minimize app footprint and our native code already uses openssl, so I need a version linked against that one.

**Comment by developernotes** [comment] 2020-04-09 21:08
Hi @akallabeth 

Can you check to see if `ndk-build` is available on your `PATH` (i.e., execute `which ndk-build`)?

**Comment by akallabeth** [comment] 2020-04-10 05:20
@developernotes yes, added it manually. Can run it in bash, path in ndk dir used (I think I had the wrong one when I created the log). same result.

**Comment by developernotes** [comment] 2020-04-10 13:18
Hi @akallabeth 

What happens when you run `make build-openssl`?

**Comment by akallabeth** [comment] 2020-04-10 16:00
@developernotes that one is building openssl, no issues.

**Comment by developernotes** [comment] 2020-04-10 16:05
Hi @akallabeth 

After attempting a build of `./gradlew android-database-sqlcipher:buildNative`, navigate into the SQLCipher directory:

```
cd android-database-sqlcipher/src/main/external/sqlcipher/
```

Do you see a `config.log` file present? If so, what is contained in the file? Do you see any errors?

**Comment by akallabeth** [comment] 2020-04-10 17:06
[config.zip](https://github.com/sqlcipher/android-database-sqlcipher/files/4462547/config.zip)

some `conftest` errors nothing I´d call suspicious, but attaching the file for review.

**Comment by developernotes** [comment] 2020-04-10 19:26
Hi @akallabeth 

Do you have `build-essential` installed? Also, it appears you are also missing Tcl.

**Comment by akallabeth** [comment] 2020-04-10 20:16
@developernotes wait, what? This is a cross compile, build-essential are host compiler tools.
Anyway, installed, compiling C related stuff every day.
The tcl part I can check tomorrow (late here)

Also tried on another machine (fedora 31 host), sadly same result.

**Comment by developernotes** [comment] 2020-04-10 20:36
Hi @akallabeth 

>wait, what? This is a cross compile, build-essential are host compiler tools.

Correct, however a part of the build process is to prepare an amalgamation of SQLCipher which is compiled with the JNI layer.

**Comment by akallabeth** [comment] 2020-04-11 07:06
Ok, ran the `ndk-build` step manually with the `environment` and `workingdir` copied from the log.
Get these lines:
```
make: Entering directory '/home/nin/src/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp'
/home/nin/Android/Sdk/ndk/21.0.6113669/build/gmsl/__gmsl:512: *** non-numeric second argument to 'wordlist' function: ''.  Stop.
make: Leaving directory '/home/nin/src/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp'
```

**Comment by developernotes** [comment] 2020-04-13 16:18
Hi @akallabeth 

Just to rule out a difference in what specific Android NDK was installed via `sdkmanager` (I don't use that directly), would you try [this](https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip) archive provided by Google? It matches the exact NDK version in `source.properties` that I am using. Thanks!

**Comment by akallabeth** [comment] 2020-04-14 07:14
@developernotes same same :/

**Comment by akallabeth** [comment] 2020-04-28 07:55
still not able to build with either `4.3.0` tag or 7d86f6bd702da7c4cb66e77b4543822fe89fe87a

**Comment by developernotes** [comment] 2020-04-28 13:13
Hi @akallabeth 

>same same :/

Would you mind clarifying what specific command and error message you received when running the command using the linked [NDK](https://github.com/sqlcipher/android-database-sqlcipher/issues/503#issuecomment-612969937)?

**Comment by akallabeth** [comment] 2020-04-28 13:16
@developernotes they are exactly the same, (maybe the line is different). (the `non-numeric` message from above)

**Comment by akallabeth** [comment] 2020-04-28 13:16
@developernotes I will retry this evening when I have time.

**Comment by akallabeth** [comment] 2020-05-13 08:10
Ok, sorry, did forget about this.
Tested this again (also with `v4.4.0`) on ubuntu 18.04 and 20.04: 
1. Installed linked NDK 
1. Installed command line sdktools, dependencies installed by gradle
1. Installed `tcl`  and `build-essentials` on host
1. Set up `ANDROID_NDK_ROOT`, `ANDROID_NDK_HOME` and `ANDROID_HOME`, `ANDROID_SDK_ROOT` (just to be sure we cover the most common variants out there)
1. Ran `make init` and `make build-debug`
1. Both fail with the same error (attached the output of the 19.04 build) [log.txt.zip](https://github.com/sqlcipher/android-database-sqlcipher/files/4620591/log.txt.zip)

**Comment by developernotes** [comment] 2020-05-13 13:29
Hi @akallabeth 

Would you rerun your `android-database-sqlcipher:buildAmalgamation` task with the `--debug` flag and provide the build output for review?

**Comment by akallabeth** [comment] 2020-05-13 14:19
[log.txt.zip](https://github.com/sqlcipher/android-database-sqlcipher/files/4622439/log.txt.zip)

ran
1. `./gradlew buildAmalgamation --debug 2>&1 |tee log.txt` 
1. `./gradlew buildNative --debug 2>&1 |tee native-log.txt`

**Comment by developernotes** [comment] 2020-05-21 21:24
Hi @akallabeth 

Is it possible you sent an old log.txt.zip file? The output in the linked log file doesn't appear to have the usually verbose debug output.

**Comment by akallabeth** [comment] 2020-05-22 15:00
@developernotes ok, that is embarrassing, yes, you´re right, uploaded the wrong zip :/ back on monday, currently only limited access to the test machine.

**Comment by akallabeth** [comment] 2020-05-25 05:40
Ran the test again, this time the correct zip.
1. `git clean -xdf`
1. `./gradlew buildAmalgamation --debug 2>&1 |tee log.txt`
1. `./gradlew buildNative --debug 2>&1 |tee native-log.txt`

[log.txt.zip](https://github.com/sqlcipher/android-database-sqlcipher/files/4675367/log.txt.zip)

**Comment by developernotes** [comment] 2020-07-10 13:36
Hi @akallabeth 

My apologizes for the delay in response. Reviewing your log, it appears this command fails. Would you try running it directly and let us know the output?

```
ndk-build V=1 NDK_DEBUG=0 --environment-overrides NDK_LIBS_OUT=/home/nin/src/android-database-sqlcipher/android-database-sqlcipher/src/main/libs32 -C /home/nin/src/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp NDK_APPLICATION_MK=/home/nin/src/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/Application32.mk
```

**Comment by akallabeth** [comment] 2020-07-23 06:09
@developernotes sorry, was on vacation, will try as soon as possible

**Comment by akallabeth** [comment] 2020-08-06 12:07
Sorry, did forget.

Here: 
```
ndk-build V=1 NDK_DEBUG=0 --environment-overrides NDK_LIBS_OUT=/home/nin/src/android-database-sqlcipher/android-database-sqlcipher/src/main/libs32 -C /home/nin/src/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp NDK_APPLICATION_MK=/home/nin/src/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/Application32.mk
make: Entering directory '/home/nin/src/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp'
/home/nin/Android/Sdk/ndk/21.3.6528147/build/gmsl/__gmsl:512: *** non-numeric second argument to 'wordlist' function: ''.  Stop.
make: Leaving directory '/home/nin/src/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp'
```

Same for other NDK versions.

**Comment by developernotes** [comment] 2020-08-14 13:12
Hi @akallabeth 

What Linux distribution and version are your running this build on?

**Comment by akallabeth** [comment] 2020-08-14 14:12
@developernotes ubuntu 20.04

**Comment by developernotes** [comment] 2020-08-31 20:18
Hi @akallabeth 

I'm sorry for the delay, I've made a few changes to the build process necessary for building on Ubuntu 20.04. I am now able to successfully but on Ubuntu 20.04. Would you mind pulling the latest changes, then run the following and let us know your results? 

```
make distclean
make build-debug
```

Thanks!

**Comment by akallabeth** [comment] 2020-09-01 09:51
@developernotes thank you, commit 41bcfa9d4a05982c4e0c0076f90b0cb5ad56d1e0 does build, even with the most recent NDK

**Comment by developernotes** [comment] 2020-09-02 13:05
Hi @akallabeth 

Excellent, that is great news, thank you for confirming on your end. I will close this issue now, thank you again for your report!

**Closed by developernotes** 2020-09-02 13:05 UTC
