### ISSUE TITLE
net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here

### ISSUE THREAD

**Issue by SyllaJay** [sqlcipher/android-database-sqlcipher#262] opened 2016-09-26 10:11 UTC
I got “net.sqlcipher.database.DatabaseObjectNotClosedException” frequently. My app use "greendao-encryption:2.2.2" and "sqlcipher:3.5.4". 
I saw #176 . Anyone can help please?

Releasing statement in a finalizer. Please ensure that you explicitly call close() on your cursor: INSERT OR REPLACE INTO "Session" ("_id","SESSION_KEY","TALK_ID","CREATED","UPDATED","COLOR","LAST_VI
                                                                             net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
                                                                                 at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:62)
                                                                                 at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:103)
                                                                                 at net.sqlcipher.database.SQLiteStatement.<init>(SQLiteStatement.java:39)
                                                                                 at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1556)
                                                                                 at de.greenrobot.dao.database.EncryptedDatabase.compileStatement(EncryptedDatabase.java:66)
                                                                                 at de.greenrobot.dao.internal.TableStatements.getInsertOrReplaceStatement(TableStatements.java:67)
                                                                                 at de.greenrobot.dao.AbstractDao.insertOrReplace(AbstractDao.java:335)
..... Our code just call insertOrReplace ......

**Comment by theBlbDan** [comment] 2016-09-26 16:26
Not seeing your code, I can only make assumptions.  I found it best to extend SQLiteOpenHelper and only bother closing cursors when I'm done with them.  Due to device rotation recycling the app, I gave up on managing the DB file closure myself and decided to let the OS and SQLiteOpenHelper class deal with that.

Here's a good resource to look over [Local Databases with SQLiteOpenHelper](https://github.com/codepath/android_guides/wiki/Local-Databases-with-SQLiteOpenHelper).

**Comment by developernotes** [comment] 2016-09-26 16:33
Hi @SyllaJay 

In conjunction with @theBlbDan's response, it is quite difficult to determine the cause of the error with the information provided. Also, it appears you are utilizing a third-party database library on top of SQLCipher for Android. Are you able to recreate an the behavior with the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)? Additional information with an isolated scenario would be beneficial in debugging this situation. Thanks!

**Comment by SyllaJay** [comment] 2016-09-27 02:43
Thanks for response.  
I just used greenDAO and Sqlcihper, refer to http://greenrobot.org/greendao/documentation/database-encryption/

Code snippet:
ps: openHelper is instance of "de.greenrobot.dao.database.EncryptedDatabaseOpenHelper"

public void batchInsertOrUpdateSession(List<SessionEntity> entityList) {
        Database db = openHelper.getWritableDatabase(mKey);
        DaoMaster daoMaster = new DaoMaster(db);
        DaoSession daoSession = daoMaster.newSession();
        SessionDao dao = daoSession.getSessionDao();
        dao.insertOrReplaceInTx(entityList);
    }

**Comment by developernotes** [comment] 2016-09-27 13:00
Hello @SyllaJay 

It appears your issue may be with greenDAO not closing the cursor. In your example, you are just getting a database connection from SQLCipher for Android, but then you pass it off to the greenDAO code for all other operations. You may wish to reach out to [them](https://github.com/greenrobot/greenDAO) for further details.

**Closed by developernotes** 2016-09-27 13:00 UTC

**Comment by SyllaJay** [comment] 2016-09-28 01:34
Thank you @developernotes . I'm working on it.

**Comment by cjztool** [comment] 2017-09-12 09:15
in my case,  greendao3.2.2, android-database-sqlcipher:3.5.7, debug build is normal,  but after release build , run my app, it shown this error,

if your proguard rules config have -overloadaggressively  , delete it ,  issue will gone..
